### ISSUE TITLE
tailwind → chakuraに置き換える？

### ISSUE THREAD

**Issue by sosukemikami3** [sgmikami03/portfolio_app#24]

**Comment by sosukemikami3** [comment]
https://github.com/sgmikami03/portfolio_app/assets/74947937/b2af3149-33f3-4e62-a6b8-4a286639d52a

**Comment by sosukemikami3** [comment]
全てchakurauiに置き換える

- [x] login
- [x] logout
- [x] signin
- [x] profile/[id]
- [x] profile/[id]/works

**Comment by Kubbo0308** [comment]
参考程度に投下
https://zenn.dev/wado63/articles/09e09151d160f3

**Comment by sosukemikami3** [comment]
ありがとう🙇

**Comment by sosukemikami3** [comment]
全ページ移行完了
tailwind を削除するだけ
